### ISSUE TITLE
ConfyUI crash at startup - clang: error: linker command failed due to signal (use -v to see invocation)

### ISSUE THREAD

**Issue by igorcirovic** [patientx/ComfyUI-Zluda#302]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

ComfyUI starts without issues

### Actual Behavior

After the latest update (at the time of opening this issue) ComfyUI fails to start.

### Steps to Reproduce

Start ComfyUI using comfyui-n.bat

### Debug Logs

```powershell
*** Checking and updating to new version if possible
Already up to date.

** Checking ZLUDA version
ZLUDA 3.9.5
Check passed.

C:\Python312\Lib\ssl.py:524: UserWarning: Bad certificate in Windows certificate store: not enough data: cadata does not contain a certificate (_ssl.c:4014)
  warnings.warn(f"Bad certificate in Windows certificate store: {exc!s}")
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-09-13 19:54:50.547
** Platform: Windows
** Python version: 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]
** Python executable: D:\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: D:\ComfyUI-Zluda
** ComfyUI Base Folder Path: D:\ComfyUI-Zluda
** User directory: D:\ComfyUI-Zluda\user
** ComfyUI-Manager config path: D:\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: D:\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI-Zluda\custom_nodes\rgthree-comfy
   4.6 seconds: D:\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
%%% [backported] imported triton knobs

  ::  Checking package versions...
Found pydantic: 2.11.7, pydantic-settings: 2.10.1
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.26.11
Installed version of comfyui-workflow-templates: 0.1.81
Installed version of av: 15.1.0
Installed version of comfyui-embedded-docs: 0.2.6
  ::  Package version check complete.

  ::  ------------------------ ZLUDA -----------------------  ::
  ::  Auto-detecting AMD GPU architecture for Triton...
  ::  Detected GPU via Windows registry: AMD Radeon RX 6900 XT
  ::  Set TRITON_OVERRIDE_ARCH=gfx1030
  ::  Triton core imported successfully
  ::  Detected Triton version: 3.4.0
  ::  Enabled cuDNN
  ::  Running Triton kernel test...
%%% [info] triton/runtime/build/platform_key: AMD64,Windows,64bit,WindowsPE
Using HIP SDK Clang.
%%% Triton is using the compiler 'C:\Program Files\AMD\ROCm\6.4\bin\clang.exe'
%%% [info] triton/runtime/build/_build: "C:\Program Files\AMD\ROCm\6.4\bin\clang.exe" C:\Users\Igor\AppData\Local\Temp\tmp36ratm_z\hip_utils.c -O3 -shared -Wno-psabi -march=native -mtune=native -o C:\Users\Igor\AppData\Local\Temp\tmp36ratm_z\hip_utils.cp312-win_amd64.pyd -LD:\ComfyUI-Zluda\venv\libs "-LC:\Program Files\AMD\ROCm\6.4\lib" -ID:\ComfyUI-Zluda\venv\Lib\site-packages\triton\backends\amd\include -IC:\Users\Igor\AppData\Local\Temp\tmp36ratm_z -IC:\Python312\Include
clang: error: linker command failed due to signal (use -v to see invocation)
  ::  Triton test failed: Command '['C:\\Program Files\\AMD\\ROCm\\6.4\\bin\\clang.exe', 'C:\\Users\\Igor\\AppData\\Local\\Temp\\tmp36ratm_z\\hip_utils.c', '-O3', '-shared', '-Wno-psabi', '-march=native', '-mtune=native', '-o', 'C:\\Users\\Igor\\AppData\\Local\\Temp\\tmp36ratm_z\\hip_utils.cp312-win_amd64.pyd', '-LD:\\ComfyUI-Zluda\\venv\\libs', '-LC:\\Program Files\\AMD\\ROCm\\6.4\\lib', '-ID:\\ComfyUI-Zluda\\venv\\Lib\\site-packages\\triton\\backends\\amd\\include', '-IC:\\Users\\Igor\\AppData\\Local\\Temp\\tmp36ratm_z', '-IC:\\Python312\\Include']' returned non-zero exit status 1.
  ::  Triton available but failed verification
  ::  Patching ONNX Runtime for ZLUDA — disabling CUDA EP.
  ::  Using ZLUDA with device: AMD Radeon RX 6900 XT [ZLUDA]
  ::  Applying core ZLUDA patches...
  ::  Triton optimizations skipped (not available)
  ::  Configuring PyTorch backends...
  ::  Disabled CUDA flash attention
  ::  Enabled math attention fallback
  ::  ZLUDA initialization complete
  ::  ------------------------ ZLUDA -----------------------  ::

Total VRAM 16368 MB, total RAM 32455 MB
pytorch version: 2.7.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 6900 XT [ZLUDA] : native
Using HIP SDK Clang.
%%% Triton is using the compiler 'C:\Program Files\AMD\ROCm\6.4\bin\clang.exe'
%%% [info] triton/runtime/build/_build: "C:\Program Files\AMD\ROCm\6.4\bin\clang.exe" C:\Users\Igor\AppData\Local\Temp\tmpn_p8sxys\hip_utils.c -O3 -shared -Wno-psabi -march=native -mtune=native -o C:\Users\Igor\AppData\Local\Temp\tmpn_p8sxys\hip_utils.cp312-win_amd64.pyd -LD:\ComfyUI-Zluda\venv\libs "-LC:\Program Files\AMD\ROCm\6.4\lib" -ID:\ComfyUI-Zluda\venv\Lib\site-packages\triton\backends\amd\include -IC:\Users\Igor\AppData\Local\Temp\tmpn_p8sxys -IC:\Python312\Include
clang: error: linker command failed due to signal (use -v to see invocation)
Traceback (most recent call last):
  File "D:\ComfyUI-Zluda\main.py", line 147, in <module>
    import execution
  File "D:\ComfyUI-Zluda\execution.py", line 16, in <module>
    import nodes
  File "D:\ComfyUI-Zluda\nodes.py", line 24, in <module>
    import comfy.diffusers_load
  File "D:\ComfyUI-Zluda\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "D:\ComfyUI-Zluda\comfy\sd.py", line 13, in <module>
    import comfy.ldm.genmo.vae.model
  File "D:\ComfyUI-Zluda\comfy\ldm\genmo\vae\model.py", line 13, in <module>
    from comfy.ldm.modules.attention import optimized_attention
  File "D:\ComfyUI-Zluda\comfy\ldm\modules\attention.py", line 35, in <module>
    from flash_attn import flash_attn_func
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\flash_attn\__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\flash_attn\flash_attn_interface.py", line 13, in <module>
    from .flash_attn_triton_amd import interface_fa as flash_attn_gpu
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\flash_attn\flash_attn_triton_amd\interface_fa.py", line 3, in <module>
    from .fwd_prefill import attention_prefill_forward_triton_impl
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\flash_attn\flash_attn_triton_amd\fwd_prefill.py", line 272, in <module>
    autotune_configs, autotune_keys = get_autotune_configs()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\flash_attn\flash_attn_triton_amd\fwd_prefill.py", line 247, in get_autotune_configs
    if is_rdna():
       ^^^^^^^^^
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\flash_attn\flash_attn_triton_amd\utils.py", line 272, in is_rdna
    return is_hip() and triton.runtime.driver.active.get_current_target().arch in ("gfx1030", "gfx1100", "gfx1101",
           ^^^^^^^^
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\flash_attn\flash_attn_triton_amd\utils.py", line 263, in is_hip
    return triton.runtime.driver.active.get_current_target().backend == "hip"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\triton\runtime\driver.py", line 30, in __getattr__
    return getattr(self._initialize_obj(), name)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\triton\runtime\driver.py", line 26, in _initialize_obj
    self._obj = self._init_fn()
                ^^^^^^^^^^^^^^^
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\triton\runtime\driver.py", line 12, in _create_driver
    return active_drivers[0]()
           ^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\triton\backends\amd\driver.py", line 555, in __init__
    self.utils = HIPUtils()
                 ^^^^^^^^^^
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\triton\backends\amd\driver.py", line 148, in __init__
    mod = compile_module_from_src(src=src, name="hip_utils", include_dirs=include_dirs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\triton\runtime\build.py", line 167, in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dirs or [], include_dirs or [], libraries or [])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\triton\runtime\build.py", line 124, in _build
    subprocess.check_call(cc_cmd, stdout=subprocess.DEVNULL)
  File "C:\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files\\AMD\\ROCm\\6.4\\bin\\clang.exe', 'C:\\Users\\Igor\\AppData\\Local\\Temp\\tmpn_p8sxys\\hip_utils.c', '-O3', '-shared', '-Wno-psabi', '-march=native', '-mtune=native', '-o', 'C:\\Users\\Igor\\AppData\\Local\\Temp\\tmpn_p8sxys\\hip_utils.cp312-win_amd64.pyd', '-LD:\\ComfyUI-Zluda\\venv\\libs', '-LC:\\Program Files\\AMD\\ROCm\\6.4\\lib', '-ID:\\ComfyUI-Zluda\\venv\\Lib\\site-packages\\triton\\backends\\amd\\include', '-IC:\\Users\\Igor\\AppData\\Local\\Temp\\tmpn_p8sxys', '-IC:\\Python312\\Include']' returned non-zero exit status 1.
```

**Comment by Dhampyr85** [comment]
I fixed my issue by uninstalling the Visual Studio components and reinstalling after a reboot

**Comment by igorcirovic** [comment]
> I fixed my issue by uninstalling the Visual Studio components and reinstalling after a reboot

Tried to do the same. Didn't help me. ComfyUI also pulled another update in the meantime, but the startup issue still persists.

**Comment by patientx** [comment]
there were similar problems in the past, look through the previous issues.

https://github.com/patientx/ComfyUI-Zluda/issues/169
https://github.com/patientx/ComfyUI-Zluda/issues/149

**Comment by igorcirovic** [comment]
@patientx Thanks for the links. This particular suggestion solved the issue for me:
https://github.com/patientx/ComfyUI-Zluda/issues/169#issuecomment-3093213972
The compilation phase when starting up ComfyUI the first time after following the steps from the linked comment was significantly slower than usual due to the compilation phase for triton, but the subsequent startup was back to normal in terms of speed.

**Comment by imathrowback** [comment]
The line `subprocess.check_call(cc_cmd, stdout=subprocess.DEVNULL)` in build.py is suppressing the actual cause of the error. if you remove the redirect of stdout to null and watch the output, you'll get more information to debug the issue. For example, you might see something like this:

`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\lib\x86\libcmt.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
C:\Program Files (x86)\Windows Kits\10\\lib\10.0.26100.0\\um\x86\uuid.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
c:\Temp\tmp5xy3_xsk\hip_utils.cp312-win_amd64.pyd : fatal error LNK1120: 8 unresolved externals
clang: error: linker command failed with exit code 1120 (use -v to see invocation)`

Which is easily fixed by running:

`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat`

ref: https://stackoverflow.com/questions/31595869/how-to-resolve-the-module-machine-type-x86-conflicts-with-target-machine-type
